// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using POLK_DOTNET.Data;

#nullable disable

namespace POLK_DOTNET.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260612183027_AddStartingLanes")]
    partial class AddStartingLanes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0-preview.3.24172.4");

            modelBuilder.Entity("POLK_DOTNET.Data.CommitteeMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CommitteeMembers");
                });

            modelBuilder.Entity("POLK_DOTNET.Data.Constitution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Constitutions");
                });

            modelBuilder.Entity("POLK_DOTNET.Data.CourseTarget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DistanceMeters")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInclineDecline")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsShaded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KillZoneMm")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Lane")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Posture")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Shoot")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("CourseTargets");
                });

            modelBuilder.Entity("POLK_DOTNET.Data.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowsClubRifle")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BankingDetailsHtml")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ClubRifleFee")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CourseTargetCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("DoubleHeaderFee")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<bool>("EnableYocoPayment")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EntryFee")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("EntryFeeDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsClubEvent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDoubleHeader")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLeagueShoot")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRegistrationOpen")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaxParticipants")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NotificationEmail")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Participants")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RegistrationCloseDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresAttendanceType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequiresClubName")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequiresDivision")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequiresSahfta")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseSameCourseForBothShoots")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("POLK_DOTNET.Data.EventParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventRegistrationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventRegistrationId");

                    b.ToTable("EventParticipants");
                });

            modelBuilder.Entity("POLK_DOTNET.Data.EventRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("AttendanceType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CellNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClubName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Division")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("GuardianIndemnityAgreed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GuardianName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("GuardianSurname")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("GunType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IndemnityAgreed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("InfoAccurateConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OtherDivision")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentReference")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RifleOwnership")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SAHFTANumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShootSelection")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SocialMediaConsent")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int?>("StartingLaneShoot1")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StartingLaneShoot2")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("YocoCheckoutId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("YocoPaymentId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("EventRegistrations");
                });

            modelBuilder.Entity("POLK_DOTNET.Data.GalleryAlbum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverImageFileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GalleryAlbums");
                });

            modelBuilder.Entity("POLK_DOTNET.Data.GalleryImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GalleryAlbumId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GalleryAlbumId");

                    b.ToTable("GalleryImages");
                });

            modelBuilder.Entity("POLK_DOTNET.Data.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasSahftaAffiliation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsJunior")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MembershipApplicationId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SahftaFee")
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MembershipApplicationId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("POLK_DOTNET.Data.MembershipApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ComplexOrBuilding")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("MembershipType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubmittedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Suburb")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MembershipApplications");
                });

            modelBuilder.Entity("POLK_DOTNET.Data.MembershipOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Features")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MembershipOptions");
                });

            modelBuilder.Entity("POLK_DOTNET.Data.SiteSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SiteSettings");
                });

            modelBuilder.Entity("POLK_DOTNET.Data.CourseTarget", b =>
                {
                    b.HasOne("POLK_DOTNET.Data.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("POLK_DOTNET.Data.EventParticipant", b =>
                {
                    b.HasOne("POLK_DOTNET.Data.EventRegistration", "EventRegistration")
                        .WithMany("Participants")
                        .HasForeignKey("EventRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventRegistration");
                });

            modelBuilder.Entity("POLK_DOTNET.Data.EventRegistration", b =>
                {
                    b.HasOne("POLK_DOTNET.Data.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("POLK_DOTNET.Data.GalleryImage", b =>
                {
                    b.HasOne("POLK_DOTNET.Data.GalleryAlbum", "GalleryAlbum")
                        .WithMany("Images")
                        .HasForeignKey("GalleryAlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GalleryAlbum");
                });

            modelBuilder.Entity("POLK_DOTNET.Data.Member", b =>
                {
                    b.HasOne("POLK_DOTNET.Data.MembershipApplication", "MembershipApplication")
                        .WithMany("Members")
                        .HasForeignKey("MembershipApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MembershipApplication");
                });

            modelBuilder.Entity("POLK_DOTNET.Data.EventRegistration", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("POLK_DOTNET.Data.GalleryAlbum", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("POLK_DOTNET.Data.MembershipApplication", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
